media: static
content:
  - name: posts
    label: Posts
    path: content/posts
      - { name: title, label: Title, type: string }
      - { name: title, label: Title, type: string }
      - { name: title, label: Title, type: string }
      - { name: title, label: Title, type: string }
      - { name: title, label: Title, type: string }
